import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import '@/app/globals.css';
import ApolloWrapper from '@/lib/apollo-wrapper';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { FinancialProvider } from '@/components/FinancialContext';

config.autoAddCss = false;

const noto = Noto_Sans_JP({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={noto.className}>
        <ApolloWrapper>
            {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
