// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateTransactionInput struct {
	Title      string  `json:"title"`
	Amount     float64 `json:"amount"`
	TypeQ      string  `json:"typeQ"`
	Date       string  `json:"date"`
	CategoryID string  `json:"categoryId"`
}

type IncomeExpenseItem struct {
	Title  string  `json:"title"`
	Amount float64 `json:"amount"`
}

type IncomeExpenseSummary struct {
	IncomeItems  []*IncomeExpenseItem `json:"incomeItems"`
	ExpenseItems []*IncomeExpenseItem `json:"expenseItems"`
	Balance      float64              `json:"balance"`
}

type Mutation struct {
}

type Query struct {
}

type Transaction struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Amount   float64   `json:"amount"`
	TypeQ    string    `json:"typeQ"`
	Date     string    `json:"date"`
	Category *Category `json:"category"`
}
